/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'boost.browser-logs': [];
        'sanctum.csrf-cookie': [];
        home: [];
        register: [];
        login: [];
        'password.request': [];
        'password.email': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        logout: [];
        dashboard: [];
        'auth.provider.disconnect': [
            {
                name: 'provider';
                required: true;
            },
        ];
        'team.index': [];
        'team.store': [];
        'team.create': [];
        'team.show': [
            {
                name: 'id';
                required: true;
            },
        ];
        'team.update': [
            {
                name: 'id';
                required: true;
            },
        ];
        'team.invite.create': [
            {
                name: 'id';
                required: true;
            },
        ];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        'password.edit': [];
        'password.update': [];
        appearance: [];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
